// Code generated by "stringer -type=ValueType"; DO NOT EDIT.

package value

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[String-0]
	_ = x[Number-1]
	_ = x[Boolean-2]
	_ = x[Identifier-3]
}

const _ValueType_name = "StringNumberBooleanIdentifier"

var _ValueType_index = [...]uint8{0, 6, 12, 19, 29}

func (i ValueType) String() string {
	if i >= ValueType(len(_ValueType_index)-1) {
		return "ValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueType_name[_ValueType_index[i]:_ValueType_index[i+1]]
}
