// Code generated by "stringer -type=TokenType -output token_string.go"; DO NOT EDIT.

package lib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STDFUNCTION-0]
	_ = x[FUNCTION-1]
	_ = x[VARIABLE-2]
	_ = x[INTTYPE-3]
	_ = x[FLOATTYPE-4]
	_ = x[STRINGTYPE-5]
	_ = x[BOOLEANTYPE-6]
	_ = x[STRINGVALUE-7]
	_ = x[NUMVALUE-8]
	_ = x[BOOLEANVALUE-9]
	_ = x[LEFTPAREN-10]
	_ = x[RIGHTPAREN-11]
	_ = x[LEFTBRACKET-12]
	_ = x[RIGHTBRACKET-13]
	_ = x[COMMA-14]
	_ = x[NEWLINE-15]
	_ = x[TAB-16]
	_ = x[ADD-17]
	_ = x[SUBTRACT-18]
	_ = x[MULTIPLY-19]
	_ = x[DIVIDE-20]
	_ = x[MODULUS-21]
	_ = x[ASSIGN-22]
	_ = x[EQUAL-23]
	_ = x[GREATER-24]
	_ = x[LESS-25]
	_ = x[GREATEREQ-26]
	_ = x[LESSEQ-27]
	_ = x[NOT-28]
	_ = x[AND-29]
	_ = x[OR-30]
	_ = x[UNKNOWNVALUE-31]
	_ = x[NONE-32]
}

const _TokenType_name = "STDFUNCTIONFUNCTIONVARIABLEINTTYPEFLOATTYPESTRINGTYPEBOOLEANTYPESTRINGVALUENUMVALUEBOOLEANVALUELEFTPARENRIGHTPARENLEFTBRACKETRIGHTBRACKETCOMMANEWLINETABADDSUBTRACTMULTIPLYDIVIDEMODULUSASSIGNEQUALGREATERLESSGREATEREQLESSEQNOTANDORUNKNOWNVALUENONE"

var _TokenType_index = [...]uint8{0, 11, 19, 27, 34, 43, 53, 64, 75, 83, 95, 104, 114, 125, 137, 142, 149, 152, 155, 163, 171, 177, 184, 190, 195, 202, 206, 215, 221, 224, 227, 229, 241, 245}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
