// Code generated by "stringer -type=TokenType -output token_string.go"; DO NOT EDIT.

package lib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STDFUNCTION-0]
	_ = x[FUNCTION-1]
	_ = x[VARIABLE-2]
	_ = x[INTTYPE-3]
	_ = x[FLOATTYPE-4]
	_ = x[STRINGTYPE-5]
	_ = x[BOOLEANTYPE-6]
	_ = x[STRINGVALUE-7]
	_ = x[NUMVALUE-8]
	_ = x[BOOLEANVALUE-9]
	_ = x[LEFTPAREN-10]
	_ = x[RIGHTPAREN-11]
	_ = x[LEFTBRACKET-12]
	_ = x[RIGHTBRACKET-13]
	_ = x[LEFTCURLY-14]
	_ = x[RIGHTCURLY-15]
	_ = x[COMMA-16]
	_ = x[NEWLINE-17]
	_ = x[TAB-18]
	_ = x[ADD-19]
	_ = x[SUBTRACT-20]
	_ = x[MULTIPLY-21]
	_ = x[DIVIDE-22]
	_ = x[MODULUS-23]
	_ = x[ASSIGN-24]
	_ = x[EQUAL-25]
	_ = x[GREATER-26]
	_ = x[LESS-27]
	_ = x[GREATEREQ-28]
	_ = x[LESSEQ-29]
	_ = x[NOT-30]
	_ = x[AND-31]
	_ = x[OR-32]
	_ = x[UNKNOWNVALUE-33]
	_ = x[NONE-34]
}

const _TokenType_name = "STDFUNCTIONFUNCTIONVARIABLEINTTYPEFLOATTYPESTRINGTYPEBOOLEANTYPESTRINGVALUENUMVALUEBOOLEANVALUELEFTPARENRIGHTPARENLEFTBRACKETRIGHTBRACKETLEFTCURLYRIGHTCURLYCOMMANEWLINETABADDSUBTRACTMULTIPLYDIVIDEMODULUSASSIGNEQUALGREATERLESSGREATEREQLESSEQNOTANDORUNKNOWNVALUENONE"

var _TokenType_index = [...]uint16{0, 11, 19, 27, 34, 43, 53, 64, 75, 83, 95, 104, 114, 125, 137, 146, 156, 161, 168, 171, 174, 182, 190, 196, 203, 209, 214, 221, 225, 234, 240, 243, 246, 248, 260, 264}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
