// Code generated by "stringer -type=TokenType -output token_string.go"; DO NOT EDIT.

package lib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IDENTIFIER-0]
	_ = x[INTTYPE-1]
	_ = x[FLOATTYPE-2]
	_ = x[STRINGTYPE-3]
	_ = x[BOOLEANTYPE-4]
	_ = x[STRINGVALUE-5]
	_ = x[NUMVALUE-6]
	_ = x[BOOLEANVALUE-7]
	_ = x[LEFTPAREN-8]
	_ = x[RIGHTPAREN-9]
	_ = x[LEFTBRACKET-10]
	_ = x[RIGHTBRACKET-11]
	_ = x[LEFTCURLY-12]
	_ = x[RIGHTCURLY-13]
	_ = x[COMMA-14]
	_ = x[NEWLINE-15]
	_ = x[TAB-16]
	_ = x[PERIOD-17]
	_ = x[SEMI-18]
	_ = x[ADD-19]
	_ = x[SUBTRACT-20]
	_ = x[MULTIPLY-21]
	_ = x[DIVIDE-22]
	_ = x[MODULUS-23]
	_ = x[ASSIGN-24]
	_ = x[EQUAL-25]
	_ = x[GREATER-26]
	_ = x[LESS-27]
	_ = x[GREATEREQ-28]
	_ = x[LESSEQ-29]
	_ = x[NOT-30]
	_ = x[AND-31]
	_ = x[OR-32]
	_ = x[UNKNOWNVALUE-33]
	_ = x[NONE-34]
}

const _TokenType_name = "IDENTIFIERINTTYPEFLOATTYPESTRINGTYPEBOOLEANTYPESTRINGVALUENUMVALUEBOOLEANVALUELEFTPARENRIGHTPARENLEFTBRACKETRIGHTBRACKETLEFTCURLYRIGHTCURLYCOMMANEWLINETABPERIODSEMIADDSUBTRACTMULTIPLYDIVIDEMODULUSASSIGNEQUALGREATERLESSGREATEREQLESSEQNOTANDORUNKNOWNVALUENONE"

var _TokenType_index = [...]uint16{0, 10, 17, 26, 36, 47, 58, 66, 78, 87, 97, 108, 120, 129, 139, 144, 151, 154, 160, 164, 167, 175, 183, 189, 196, 202, 207, 214, 218, 227, 233, 236, 239, 241, 253, 257}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
